// <auto-generated />
namespace Bookify.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddFilePathsToBook : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddFilePathsToBook));
        
        string IMigrationMetadata.Id
        {
            get { return "202411111927135_AddFilePathsToBook"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
